server:
  port: 9000
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: orderbook-maker

app:
  id: orderbook-maker

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: orderbook-maker
  endpoint:
    health:
      show-details: always
